### PR TITLE
fixes issues 82 and 83

### LINKED ISSUE #83: Notes for R Fundamentals Pt 2
Line 55 - install.packages("here") is missing quotes

### PR DESCRIPTION
**Pull request by asteves**
fixes and closes issues #83 #82 

-Ordering is now done by the Area column, which will lead to a change in order in the data frame. 
-the here install.packages() function now includes ""

### CODE REVIEW

**Comment by asteves** [comment]
@pssachdeva These are easy one liners, but I'm not sure if you want to merge them in when a workshop is going hence the review request.

**Comment by seanmperez** [comment]
See updates in #82.

**Comment by asteves** [comment]
Updated to address @seanmperez comment.

**Comment by seanmperez** [comment]
@asteves looks good! Thanks for addressing this so quickly!

**Pull request merged**
