### PR TITLE
change poor language to coherence check

### LINKED ISSUE #106: Remove references to sanity checks
https://github.com/dlab-berkeley/R-Fundamentals/blob/c7ae443cac0ca0d6955774d131479697a84ca3b0/lessons/Part1.R#L217

Change references to "sanity checks" to something like "confidence checks" (one case linked above)

See [here](https://gist.github.com/seanmhanson/fe370c2d8bd2b3228680e38899baf5cc) for more details

### PR DESCRIPTION
**Pull request by asteves**
This PR closes #106 by changing the language flagged to coherence check.

### CODE REVIEW

**Comment by pssachdeva** [comment]
I think I'd actually prefer something like "assumptions check" or "confidence check" which I think are little closer to the implied connotation. The first thing I think of when I hear "coherence" is coherence in a medical sense (e.g., is someone coherent after hitting their head).

**Comment by asteves** [comment]
Sounds good. I can update to confidence check. Assumption check seems off
to me in context.

**Comment by asteves** [comment]
@pssachdeva Updated to confidence check.

**Review by pssachdeva — APPROVED** [review]

**Comment by pssachdeva** [comment]
feel free to merge next week (R Fundamentals is happening right now)

**Comment by asteves** [comment]
Sounds good.

**Pull request merged**
