### PR TITLE
Updates Part1.R

### LINKED ISSUE #26: Part 1: use variable number
We define the variable "number" and assign 5 to it but don't use it to demonstrate how to use a variable. Might be good to add one line like "number + 8" to show that we can use the variable like a number (which it is).  I would add that right after the line "class(number)"

### LINKED ISSUE #27: Part 1: Remove or adjust sentence formation block in Section 5
In lines 163-195, several functions operating on character objects are demonstrated and used. This is probably not necessary for the very first lesson in R. Furthermore, they don't fit the section, which aims to demonstrate data structures (vectors, lists, and data frames).

They should be removed from this section. They could potentially be excised entirely, or placed in the section which introduces built-in functions.

### LINKED ISSUE #28: Part 1: Remove random number generation
It is probably not necessary to introduce random number generation in the very first lesson. It can be confusing for first time users and is not necessary to create dataframes - we can just create the dataframes by hand.

Furthermore, this concept is also brought up in Part 4. It could be moved to that lesson entirely.

### LINKED ISSUE #29: Part 1: Move introduction of factors
Factors are mentioned near the end of the lesson, *after* the introduction of data frames. This is likely to explain the `stringsAsFactors` parameter for data frames.

This is likely not necessary. First, `stringsAsFactors` can simply be omitted here: the default argument is `FALSE`, so it doesn't need to be discussed at all. It can be brought up in Part 2 if necessary.

The introduction of factors should occur with the other data types. It's a little odd that it's mentioned in the beginning of that section, but not referenced till much later in the lesson.

### LINKED ISSUE #30: Part 1: Remove scientific notation function
Line 220, defining the scientific notation, comes somewhat abruptly. It is likely not necessary to demonstrate usage of this function. Its use case is not motivated and it is not referenced again in this lesson, so it makes the momentum of the lesson feel a bit awkward.

### LINKED ISSUE #31: Part 1: Move Section 8 to Part 2
Section 8 discusses `getwd()` and saving a csv file. This comes a little bit out of nowhere, and would fit naturally in Part 2 when importing csv files from a specific path is discussed.

### LINKED ISSUE #32: Part 1: Make a note about assigment operators (= and <-)
There should be a short example demonstrating that = can be used for assignment in R, but <- is preferable due to style (and that in specific examples that don't need to be detailed at the time, they do in fact behave differently).

### PR DESCRIPTION
**Pull request by pssachdeva**
The following changes are made:
- Almost all comments and text have been fleshed out, standardized, and formalized.
- Section headers have been standardized.
- Number of hashtags have been standardized. One hashtag for sections, two for normal comments, three for challenges.
- Variable assignment is discussed in more detail, including the equals sign (Closes #32) and some arithmetic is discussed (Closes #26)
- Named arguments in functions are discussed
- A section on factors is referenced before data frames (Closes #29).
- Removal of string manipulation entirely (Closes #27).
- Revamping of data frames section to avoid using random number generation (Closes #28)
- Removal of scientific notation code (Closes #30)
- Removal of section 8 (Closes #31).

### CODE REVIEW

**Comment by pssachdeva** [comment]
@joseaveldanes, you're doing the next set of R Fundamentals. Could you take a look at this, run through it, and let me know if there are any glaring issues?

Also welcome any feedback from @Averysaurus.

**Review by asteves — COMMENTED** [review]
Line 45 in proposed commit. Is there any function in R for which this is not true? I cannot think of one and so perhaps can drop the usually. 

Line 82: rm(list = ls()) removes any user created variable, which includes function. Do we want to teach people the full kill switch, or just instead rm(c(VARIABLE NAMES))

**Comment by pssachdeva** [comment]
Thanks for the feedback, @asteves. I addressed both your comments in the most recent commit.

**Comment by joseaveldanes** [comment]
Hi Pratik, 

I managed to look over Part I over the weekend and it looked good! I will be sure to commit any changes I make but will get to the rest of the materials this week. 

All my best, 
José Martín Aveldanes
​Ph.D​ Student in Sociology
University of California, Berkeley ​
Social Sciences Building, Berkeley 
CA, 94720

**Comment by asteves** [comment]
@pssachdeva LGTM

**Comment by pssachdeva** [comment]
@joseaveldanes, is this good to go? You mentioned you had some comments. I'd like to merge this soon (but perhaps after you teach Part 1 tomorrow).

**Comment by joseaveldanes** [comment]
Hi Pratik, 

I reviewed the first half of the series and it looks good. Sorry—it has been a crazy week this past week and a half. I will create an issue and push up that code. I am going to look through the protocol guide because I am actually a little confused about how to show you the new code without pushing to the master branch. 

All my best, 
José Martín Aveldanes
​Ph.D​ Student in Sociology
University of California, Berkeley ​
Social Sciences Building, Berkeley 
CA, 94720

**Comment by pssachdeva** [comment]
@joseaveldanes It's probably easiest if you just comment on the pull request directly about what changes you want to see happen. Or, you can push onto my branch directly. Happy to chat over Zoom if you want to walk through either process.

**Comment by joseaveldanes** [comment]
I figured it out! Looking over the code with all the fixed components—I think this looks nice and clean. I think it went smoothly today in teaching Part I (and Part II). You can go ahead and push up and if I see any glaring issues for Parts III and IV, I know how to make that an issue and will send it your way for review. Sorry for the delay on this, I had looked at the code before and had spent a good chunk of time just figuring out how to teach it (and reviewing it) as prep since it is the very first time I have ever taught a workshop! 

Thanks so much. 

All my best,
José Martín Aveldanes
​Ph.D​ Student in Sociology
University of California, Berkeley ​
Social Sciences Building, Berkeley 
CA, 94720

**Comment by pssachdeva** [comment]
Great, I am merging now.

**Pull request merged**
